use case_study_m3;
insert into users values
                      (default, 'son94', '123456', 'Nguyen Hai Son', 'Ha Nam', 'son@gmail.com'),
                      (default, 'nam95', '123456', 'Nguyen Hoai Nam', 'Ha Noi', 'nam@gmail.com'),
                      (default, 'adua2001', '123456', 'Giang A Dua', 'Bac Ninh', 'adua@gmail.com'),
                      (default, 'tuuyen2001', '123456', 'Dinh Thi Tu Uyen', 'Ha Noi', 'uyen@gmail.com'),
                      (default, 'tuan97', '123456', 'PHam Minh Tuan', 'Ha Noi', 'tuan@gmail.com'),
                      (default, 'hung97', '123456', 'Nguyen Nhu Hung', 'Nam Dinh', 'hung@gmail.com'),
                      (default, 'congnghien97', '123456', 'Pham Minh Cong', 'Bac Ninh', 'cong@gmail.com'),
                      (default, 'hai96', '987654321', 'Ngo Hoang Hai', 'Ha Noi', 'hai@gmail.com'),
                      (default, 'hai00', '234567','Do Trong Hai', 'Bac Ninh', 'haido@gmail.com'),
                      (default, 'hieu96', '3445778', 'Dang Manh Hieu', 'Nam Dinh', 'hieu@gmail.com');

<<<<<<< HEAD
insert into songs values
                      (default, 'Khong yeu', 'sonson',default, 'abc', 10, 'nhac tre', 1, default),
                      (default, 'Yeu khong', 'sonson',default, 'abc', 110, 'nhac tre', 1,default),
                      (default, 'Em la ai', 'sonson',default, 'abc', 31, 'pop', 1, default),
                      (default, 'Anh la ai', 'sonson',default, 'abc', 41, 'nhac gia', 2, default),
                      (default, 'Day la dau', 'sonson',default, 'abc', 41, 'nhac vang', 2, default),
                      (default, 'Em o dau', 'sonson',default, 'abc', 671, 'pop', 3, default),
                      (default, 'Anh o dau', 'sonson',default, 'abc', 451, 'jar', 3, default),
                      (default, 'Lan dau gap go', 'sonson',default, 'abc', 341, 'pop', 4, default),
                      (default, 'Khong yeu', 'sonson',default, 'abc', 431, 'nhac tre', 5, default),
                      (default, 'Toi la ai', 'sonson', default, 'abc', 341, 'nhac ma', 6, default),
                      (default, 'Day la dau', 'sonson', default, 'abc', 331, 'rock', 4, default),
                      (default, 'Toi la dau', 'sonson', default, 'abc', 431, 'nhac tre', 7, default),
                      (default, 'Day la ai', 'sonson', default, 'abc', 143, 'pop', 5, default),
                      (default, 'Chau len ba', 'sonson', default, 'abc', 341, 'nhac thieu nhi', 7, default),
                      (default, 'Chau len bon', 'sonson', default, 'abc', 231, 'nhac thieu nhi', 8, default),
                      (default, 'Chau len nam', 'sonson', default, 'abc', 431, 'nhac vang', 9, default),
                      (default, 'Chau len sau', 'sonson', default, 'abc', 123, 'nhac buon', 7, default),
                      (default, 'Chau len bay', 'sonson', default, 'abc', 134, 'jar', 1, default),
                      (default, 'Chau len tam', 'sonson', default, 'abc', 153, 'pop', 6, default),
                      (default, 'Chau len chin', 'sonson', default, 'abc', 124, 'classical', 9, default),
                      (default, 'Chau len muoi', 'sonson', default, 'abc', 143, 'nhac tre', 10, default),
                      (default, 'La anh', 'sonsosn', default, 'abc', 133, 'nhac tre', 5, default),
                      (default, 'La em' , 'sonson', default, 'abc', 20, 'pop', 3, default),
                      (default, 'Fake love', 'BTS', default, 'abc', 500, 'K-pop', 2, default),
                      (default, 'Trouble Im in', 'Twinbed', default, 'abc',100,  'pop', 1, default),
                      (default, 'An nut tha giac mo', 'Son Tung', default, 'abc', 200, 'pop', 6, default),
                      (default, 'Dong kiem em','vu',default,'abc',200,'v-pip',7, default ),
                      (default,'La lung','vu',default,'abc',300,'v-pop',8, default),
                      (default,'Buoc qua mua co don','Vu',default,'abc',300,'V-pop',10, default),
                      (default,'Con mua ngang qua','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'em cua hom wua','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Am tham ben em','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Chac yeu la day','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Chay ngay di','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Lac troi','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'EM dung di','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Anh sai roi','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Nang am xa dan','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Chung ta khong thuoc ve nhau','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Chac ai do se ve','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Khong ai thuong em nhu anh','Bao Anh',default,'abc',300,'V-pop',6, default),
                      (default,'Em gai mua','Huong tram',default,'abc',300,'V-pop',7, default),
                      (default,'Duyen minh lo','Huong tram',default,'abc',300,'V-pop',9, default),
                      (default,'la em','Mo no',default,'abc',300,'V-pop',2, default),
                      (default,'Em cua qua khu','Son tung',default,'abc',300,'V-pop',5, default),
                      (default,'Chung ta cua hien tai','Son tung',default,'abc',300,'V-pop',5, default);
=======
insert into songs(s_id, song_name, author, upload_date, url, listening_frequency, label, u_id) values
(default, 'Khong yeu', 'sonson',default, 'abc', 1, 'nhac tre', 1),
(default, 'Yeu khong', 'sonson',default, 'abc', 1, 'nhac tre', 1),
(default, 'Em la ai', 'sonson',default, 'abc', 1, 'pop', 1),
(default, 'Anh la ai', 'sonson',default, 'abc', 1, 'nhac gia', 2),
(default, 'Day la dau', 'sonson',default, 'abc', 1, 'nhac vang', 2),
(default, 'Em o dau', 'sonson',default, 'abc', 1, 'pop', 3),
(default, 'Anh o dau', 'sonson',default, 'abc', 1, 'jar', 3),
(default, 'Lan dau gap go', 'sonson',default, 'abc', 1, 'pop', 4),
(default, 'Khong yeu', 'sonson',default, 'abc', 1, 'nhac tre', 5),
(default, 'Toi la ai', 'sonson', default, 'abc', 1, 'nhac ma', 6),
(default, 'Day la dau', 'sonson', default, 'abc', 1, 'rock', 4),
(default, 'Toi la dau', 'sonson', default, 'abc', 1, 'nhac tre', 7),
(default, 'Day la ai', 'sonson', default, 'abc', 1, 'pop', 5),
(default, 'Chau len ba', 'sonson', default, 'abc', 1, 'nhac thieu nhi', 7),
(default, 'Chau len bon', 'sonson', default, 'abc', 1, 'nhac thieu nhi', 8),
(default, 'Chau len nam', 'sonson', default, 'abc', 1, 'nhac vang', 9),
(default, 'Chau len sau', 'sonson', default, 'abc', 1, 'nhac buon', 10),
(default, 'Chau len bay', 'sonson', default, 'abc', 1, 'jar', 10),
(default, 'Chau len tam', 'sonson', default, 'abc', 1, 'pop', 9),
(default, 'Chau len chin', 'sonson', default, 'abc', 1, 'classical', 7),
(default, 'Chau len muoi', 'sonson', default, 'abc', 1, 'nhac tre', 8);
insert into playlist values
(default, 'Ua thich cua Son', default, 1,'nhac tre'),
(default, 'Son hay nghe', default, 1,'nhac vang'),
(default, 'Ua thich cua Nam', default, 2,'rock'),
(default, 'Ua thich cua Dua', default, 3,'jar'),
(default, 'Ua thich cua Uyen', default, 4,'pop');
>>>>>>> f1ee920402ae2aebf909aca386d09faa360df382


insert into playlist values
                         (default, 'Ua thich cua Son', default, 1,'Nhac Vpop'),
                         (default, 'Son hay nghe', default, 1,'Nhac kpop'),
                         (default, 'Nhac son cuong', default, 1,'Nhac tre'),
                         (default, 'Nhac chua lanh son', default, 1,'Nhac khong loi'),
                         (default, 'Nhac son ghet', default, 1,'nhac vang'),
                         (default, 'Ua thich cua Uyen', default, 4,'nhac khong loi'),
                         (default, 'Uyen hay nhghe', default, 4,'Nhac kpop'),
                         (default, 'Ua thich cua Tuan', default, 5,'Nhac tre'),
                         (default, 'Ua thich cua Hung', default, 6,'Nhac EDM'),
                         (default, 'Ua thich cua Cong', default, 7,'nhac buon'),
                         (default, 'Ua thich cua Hai96', default, 8,'Nhac EMD'),
                         (default, 'Ua thich cua Hai2000', default, 9,'Nhac Vang'),
                         (default, 'Ua thich cua Hieu96', default, 10,'Nhac Buon'),
                         (default, 'Nghe nhieu cua Tuan', default, 5,'Nhac Vang'),
                         (default, 'Nghe nhieu cua Hung', default, 6,'Nhac Buon'),
                         (default, 'Nghe nhieu cua Cong', default, 7,'Nhac Vang'),
                         (default, 'Nghe nhieu cua Hai96', default, 8,'Nhac VPOP'),
                         (default, 'Nghe nhieu cua Hai200', default, 9,'Nhac Vang'),
                         (default, 'Nghe nhieu cua Hieu96', default, 5,'Nhac Kpop'),
                         (default, 'Dua khong thich nghe', default, 3,'Nhac Vang');

insert into playlist_detail values
                                (default, 1, 1),
                                (default, 2, 1),
                                (default, 4, 1),
                                (default, 2, 2),
                                (default, 5, 2),
                                (default, 9, 2),
                                (default, 1, 2),
                                (default, 4, 3),
                                (default, 3, 3),
                                (default, 6, 3),
                                (default, 7, 3),
                                (default, 8, 1),
                                (default, 9, 4),
                                (default, 3, 4),
                                (default, 2, 4),
                                (default, 5, 4),
                                (default, 4, 7),
                                (default, 4, 10),
                                (default, 40, 13),
                                (default, 22, 12),
                                (default, 23, 14),
                                (default, 30, 6),
                                (default, 19, 5),
                                (default, 45, 13),
                                (default, 33, 2),
                                (default, 10, 10),
                                (default, 7, 7),
                                (default, 25, 5),
                                (default, 7, 8),
                                (default, 18, 8),
                                (default, 12, 12),
                                (default, 6, 9);
