use case_study_m3;
insert into users (u_id, user_name, password, fullname, address, email)
values (default, 'son94', '123456', 'Nguyễn Hải Sơn', 'Hà Nam', 'son@gmail.com'),
       (default, 'nam95', '123456', 'Nguyễn Hoài Nam', 'Hà Nội', 'nam@gmail.com'),
       (default, 'adua2001', '123456', 'Giàng A Dủa', 'Bắc Ninh', 'adua@gmail.com'),
       (default, 'tuuyen2001', '123456', 'Đinh Tú Uyên', 'Hà Nội', 'uyen@gmail.com'),
       (default, 'tuan97', '123456', 'Phạm Minh Tuấn', 'Hà Nội', 'tuan@gmail.com'),
       (default, 'hung97', '123456', 'Nguyễn Như Hùng', 'Nam Định', 'hung@gmail.com'),
       (default, 'congnghien97', '123456', 'Phạm Minh Công', 'Bắc Ninh', 'cong@gmail.com'),
       (default, 'hai96', '987654321', 'Ngô Hoàng Hải', 'Ha Noi', 'hai@gmail.com'),
       (default, 'hai00', '234567', 'Đỗ Trọng Hải', 'Bắc Ninh', 'haido@gmail.com'),
       (default, 'hieu96', '3445778', 'Đặng Mạnh Hiếu', 'Nam Định', 'hieu@gmail.com');

insert into songs
values (default, 'Không yêu', 'sonson', default, 'abc', 10, 'Nhạc trẻ', 1, default),
       (default, 'Yêu không', 'sonson', default, 'abc', 110, 'Nhạc trẻ', 1, default),
       (default, 'Em là ai', 'sonson', default, 'abc', 31, 'Pop', 1, default),
       (default, 'Anh là ai', 'sonson', default, 'abc', 41, 'Nhạc già', 2, default),
       (default, 'Đây là đâu', 'sonson', default, 'abc', 41, 'Nhạc vàng', 2, default),
       (default, 'Em ở đâu', 'sonson', default, 'abc', 671, 'Pop', 3, default),
       (default, 'Anh ở đâu', 'sonson', default, 'abc', 451, 'Jar', 3, default),
       (default, 'Lần đầu gặp gỡ', 'sonson', default, 'abc', 341, 'Pop', 4, default),
       (default, 'Không yêu đâu', 'sonson', default, 'abc', 431, 'Nhạc trẻ', 5, default),
       (default, 'Tôi là ai', 'sonson', default, 'abc', 341, 'Nhạc ma', 6, default),
       (default, 'Đây là đâu', 'sonson', default, 'abc', 331, 'Rock', 4, default),
       (default, 'Tôi là đâu', 'sonson', default, 'abc', 431, 'Nhạc trẻ', 7, default),
       (default, 'Đây là ai', 'sonson', default, 'abc', 143, 'Pop', 5, default),
       (default, 'Cháu lên ba', 'sonson', default, 'abc', 341, 'Nhạc thiếu nhi', 7, default),
       (default, 'Cháu lên bốn', 'sonson', default, 'abc', 231, 'Nhạc thiếu nhi', 8, default),
       (default, 'Cháu lên năm', 'sonson', default, 'abc', 431, 'Nhạc vàng', 9, default),
       (default, 'Cháu lên sáu', 'sonson', default, 'abc', 123, 'Nhạc buồn', 7, default),
       (default, 'Cháu lên bảy', 'sonson', default, 'abc', 134, 'Jar', 1, default),
       (default, 'Cháu lên tám', 'sonson', default, 'abc', 153, 'Pop', 6, default),
       (default, 'Cháu lên chín', 'sonson', default, 'abc', 124, 'Classical', 9, default),
       (default, 'Cháu lên mười', 'sonson', default, 'abc', 143, 'Nhạc trẻ', 10, default),
       (default, 'Là anh', 'sonsosn', default, 'abc', 133, 'Nhạc trẻ', 5, default),
       (default, 'Là em', 'sonson', default, 'abc', 20, 'Pop', 3, default),
       (default, 'Fake love', 'BTS', default, 'abc', 500, 'K-pop', 2, default),
       (default, 'Trouble Im in', 'Twinbed', default, 'abc', 100, 'Pop', 1, default),
       (default, 'Ấn nút thả giấc mơ', 'Son Tung', default, 'abc', 200, 'Pop', 6, default),
       (default, 'Đông kiếm em', 'vu', default, 'abc', 200, 'v-pip', 7, default),
       (default, 'Lạ lùng', 'Vũ', default, 'abc', 300, 'V-pop', 8, default),
       (default, 'Bước qua mùa cô đơn', 'Vũ', default, 'abc', 300, 'V-pop', 10, default),
       (default, 'Cơn mưa ngang qua', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Em của hôm qua', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Âm thầm bên em', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Chắc yêu là đây', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Chạy ngay đi', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Lạc trôi', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Em đừng đi', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Anh sai rồi', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Nắng ấm xa dần', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Chúng ta không thuộc về nhau', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Chắc ai đó sẽ về', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Không ai thương em như anh', 'Bảo Anh', default, 'abc', 300, 'V-pop', 6, default),
       (default, 'Em gái mưa', 'Hương Tràm', default, 'abc', 300, 'V-pop', 7, default),
       (default, 'Duyên mình lỡ', 'Hương Tràm', default, 'abc', 300, 'V-pop', 9, default),
       (default, 'là em', 'Mo no', default, 'abc', 300, 'V-pop', 2, default),
       (default, 'Em của quá khứ', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default),
       (default, 'Chúng ta của hiện tại', 'Sơn Tùng', default, 'abc', 300, 'V-pop', 5, default);


insert into playlist
values (default, 'Ưa thích của sơn', default, 1, 'Nhạc Vpop'),
       (default, 'Sơn hay nghe', default, 1, 'Nhạc Kpop'),
       (default, 'Nhạc Sơn cuồng', default, 1, 'Nhạc trẻ'),
       (default, 'Nhạc chữa lành Sơn', default, 1, 'Nhạc không lời'),
       (default, 'Nhạc Sơn ghét', default, 1, 'Nhạc vàng'),
       (default, 'Ưa thích của Uyên', default, 4, 'Nhạc không lời'),
       (default, 'Uyên hay nhghe', default, 4, 'Nhạc kpop'),
       (default, 'Ưa thích của Tuấn', default, 5, 'Nhạc trẻ'),
       (default, 'Ưa thích của Hùng', default, 6, 'Nhạc EDM'),
       (default, 'Ưa thích của Công', default, 7, 'Nhạc buồn'),
       (default, 'Ưa thích của Hải96', default, 8, 'Nhạc EDM'),
       (default, 'Ưa thích của Hải2000', default, 9, 'Nhạc vàng'),
       (default, 'Ưa thích của Hiếu96', default, 10, 'Nhạc buồn'),
       (default, 'Nghe nhiều của Tuấn', default, 5, 'Nhạc vàng'),
       (default, 'Nghe nhiều của Hùng', default, 6, 'Nhạc buồn'),
       (default, 'Nghe nhiều của Công', default, 7, 'Nhạc vàng'),
       (default, 'Nghe nhiều của Hải96', default, 8, 'Nhạc Kpop'),
       (default, 'Nghe nhiều của Hải2000', default, 9, 'Nhạc vàng'),
       (default, 'Nghe nhiều của Hiếu96', default, 5, 'Nhạc Kpop'),
       (default, 'Dủa không thích nghe', default, 3, 'Nhạc Vpop'),
       (default, 'Nam không thích nghe', default, 2, 'Nhạc Vpop'),
       (default, 'Uyên không thích nghe', default, 4, 'Nhạc Vpop'),
       (default, 'Hải không thích nghe', default, 8, 'Nhạc Vpop'),
       (default, 'Hùng không thích nghe', default, 6, 'Nhạc Kpop'),
       (default, 'Tuấn không thích nghe', default, 5, 'Nhạc Kpop'),
       (default, 'Sơn rất thích nghe', default, 3, 'Nhạc Kpop'),
       (default, 'Nam rất thích nghe', default, 2, 'Nhạc EDM'),
       (default, 'Dủa rất thích nghe', default, 3, 'Nhạc EDM'),
       (default, 'Tuấn rất thích nghe', default, 5, 'Nhạc EDM'),
       (default, 'Uyên rất thích nghe', default, 4, 'Nhạc EDM');
insert into playlist_detail
values (1, 1),
       (2, 1),
       (4, 1),
       (2, 2),
       (5, 2),
       (9, 2),
       (1, 2),
       (4, 3),
       (3, 3),
       (6, 3),
       (7, 3),
       (8, 1),
       (9, 4),
       (3, 4),
       (2, 4),
       (5, 4),
       (4, 7),
       (4, 10),
       (40, 13),
       (22, 12),
       (23, 14),
       (30, 6),
       (19, 5),
       (45, 13),
       (33, 2),
       (10, 10),
       (7, 7),
       (25, 5),
       (7, 8),
       (18, 8),
       (12, 12),
       (6, 9),
       (46, 20),
       (20,20),
       (30,20),
       (12,21),
       (13,21),
       (14,21),
       (15,22),
       (16,22),
       (17,22),
       (18,22),
       (1,23),
       (2,23),
       (3,23),
       (4,23),
       (4,24),
       (5,24),
       (6,24),
       (7,25),
       (8,25),
       (9,25),
       (10,25),
       (11,26),
       (12,26),
       (13,26),
       (14,26),
       (17,26),
       (30,27),
       (32,27),
       (33,28),
       (38,28),
       (40,29),
       (46,29),
       (44,30);

